apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 00-namespace.yaml
  - backend.yaml
  - configmap.yaml
  - frontend.yaml
  - hpa.yaml
  - ingress.yaml
  - pdb.yaml
  - postgres-secret.yaml
  - postgres.yaml
  - redis.yaml
  - vpa.yaml
