apiVersion: v1
kind: Secret
metadata:
  name: civicpulse-secrets
  namespace: civicpulse
type: Opaque
stringData:
  POSTGRES_PASSWORD: "changeme"
  GROQ_API_KEY: "changeme"
  DATABASE_URL: "postgresql+psycopg2://postgres:changeme@postgres:5432/civicpulse"
  REDIS_URL: "redis://redis:6379/0"